// Code generated by hertz generator.

package feed

import (
	"context"
	feed "dousheng/biz/model/feed"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"time"
)

var DemoVideos = []*feed.Video{
	{
		ID:            1,
		Author:        &DemoUser,
		Title:         "test title",
		PlayURL:       "https://www.w3schools.com/html/movie.mp4",
		CoverURL:      "https://cdn.pixabay.com/photo/2016/03/27/18/10/bear-1283347_1280.jpg",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
	},
}

var DemoUser = feed.User{
	ID:            1,
	Name:          "TestUser",
	FollowCount:   0,
	FollowerCount: 0,
	IsFollow:      false,
}

// Feed .
// @router /douyin/feed/ [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	//resp := new(feed.FeedResponse)

	resp := feed.FeedResponse{
		StatusCode: feed.Code_Success,
		StatusMsg:  "Success",
		NextTime:   time.Now().Unix(),
		VideoList:  DemoVideos,
	}

	c.JSON(consts.StatusOK, resp)
}
