// Code generated by hertz generator.

package main

import (
	"context"
	"dousheng/biz/dal"
	"dousheng/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/pprof"
	"time"
)

func Init() {
	dal.Init()
	mw.InitJwt()
}

// AccessLog 日志中间件
func AccessLog() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		start := time.Now()
		ctx.Next(c)
		end := time.Now()
		latency := end.Sub(start).Microseconds
		hlog.CtxTracef(c, "status=%d cost=%d method=%s full_path=%s client_ip=%s",
			ctx.Response.StatusCode(), latency,
			ctx.Request.Header.Method(), ctx.Request.URI(), ctx.ClientIP())
	}
}

func main() {
	Init()
	h := server.Default()
	h.Use(AccessLog())
	// 注册 pprof 中间件
	// 缺省为 "debug/pprof"
	pprof.Register(h, "pprof")

	register(h)
	h.Spin()
}
