// Code generated by hertz generator.

package relation

import (
	"context"
	"dousheng/biz/dal/mysql"
	relation "dousheng/biz/model/relation"
	"dousheng/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// RelationAction 关注操作
// @router /douyin/relation/action/ [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.RelationActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	v, _ := c.Get(mw.IdentityKey)
	userId := int64(v.(*mysql.UserRaw).ID)

	resp := &relation.RelationActionResponse{
		StatusCode: relation.Code_Success,
		StatusMsg:  "Success",
	}
	if req.GetActionType() == 1 {
		// 关注操作
		err := mysql.CreateRelation(ctx, userId, req.GetToUserID())
		if err != nil {
			return
		}
	} else if req.GetActionType() == 2 {
		// 取消关注操作
		err := mysql.DeleteRelation(ctx, userId, req.GetToUserID())
		if err != nil {
			return
		}
	} else {
		// 如果 action type 不为 1 或 2 则报错
		resp = &relation.RelationActionResponse{
			StatusCode: relation.Code_Error,
			StatusMsg:  "Wrong action type",
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// FollowList 获取关注列表
// @router /douyin/relation/follow/list/ [GET]
func FollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.FollowListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	v, _ := c.Get(mw.IdentityKey)
	userId := int64(v.(*mysql.UserRaw).ID)

	followIds, err := mysql.QueryFollowById(ctx, req.GetUserID())
	if err != nil {
		return
	}

	var userList []*relation.User
	err = QueryUserListByIds(ctx, userId, followIds, &userList)
	if err != nil {
		return
	}

	resp := relation.FollowListResponse{
		StatusCode: relation.Code_Success,
		StatusMsg:  "Success",
		UserList:   userList,
	}

	c.JSON(consts.StatusOK, resp)
}

// FollowerList 获取粉丝列表
// @router /douyin/relation/follower/list/ [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.FollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	v, _ := c.Get(mw.IdentityKey)
	userId := int64(v.(*mysql.UserRaw).ID)

	followerIds, err := mysql.QueryFollowerById(ctx, req.GetUserID())
	if err != nil {
		return
	}

	var userList []*relation.User
	err = QueryUserListByIds(ctx, userId, followerIds, &userList)
	if err != nil {
		return
	}

	resp := relation.FollowerListResponse{
		StatusCode: relation.Code_Success,
		StatusMsg:  "Success",
		UserList:   userList,
	}

	c.JSON(consts.StatusOK, resp)
}

func QueryUserListByIds(ctx context.Context, userId int64, ids []*int64, userList *[]*relation.User) error {
	users, err := mysql.QueryUserByIds(ctx, ids)
	if err != nil {
		return err
	}

	for _, u := range users {
		*userList = append(*userList, &relation.User{
			ID:            int64(u.ID),
			Name:          u.Name,
			FollowCount:   u.FollowerCount,
			FollowerCount: u.FollowCount,
			IsFollow:      mysql.CheckIsFollow(ctx, userId, int64(u.ID)),
		})
	}
	return nil
}
