// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	feed "dousheng/biz/router/feed"
	publish "dousheng/biz/router/publish"
	relation "dousheng/biz/router/relation"
	user "dousheng/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	publish.Register(r)

	relation.Register(r)

	user.Register(r)

	feed.Register(r)
}
